# This playbook installs the latest version of Apache

- name: Ensure apache is at the latest version
  become: yes # become root
  ansible.builtin.apt:
    name: apache2
    state: latest

- name: Update the apache2 configuration file
  become: yes # become root
  ansible.builtin.template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart apache

- name: Ensure that apache is running
  become: yes # become root
  ansible.builtin.service:
    name: apache2
    state: started
