# This playbook installs the latest version of PHP

- name: Ensure that php and php-mysql is at the latest version
  become: yes # become root
  ansible.builtin.apt:
    name:
      - php
      - php-mysql
    state: latest
